// Curated emoji picker data for folder icons. Each entry carries a few plain-English
// keywords so the picker's search bar can match on words like "pizza" or "heart"
// rather than requiring the user to already know which emoji they want.

export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  name: string;
  label: string;
  emojis: EmojiEntry[];
}

export const DEFAULT_FOLDER_EMOJI = "📁";

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Food",
    label: "Food 🍕",
    emojis: [
      { char: "🍕", keywords: ["pizza"] },
      { char: "🍔", keywords: ["burger", "hamburger"] },
      { char: "🍟", keywords: ["fries", "french fries"] },
      { char: "🌭", keywords: ["hot dog"] },
      { char: "🍿", keywords: ["popcorn"] },
      { char: "🧁", keywords: ["cupcake", "muffin"] },
      { char: "🍰", keywords: ["cake", "shortcake"] },
      { char: "🍩", keywords: ["donut", "doughnut"] },
      { char: "🍪", keywords: ["cookie"] },
      { char: "🍫", keywords: ["chocolate"] },
      { char: "🍬", keywords: ["candy", "sweet"] },
      { char: "🍭", keywords: ["lollipop"] },
      { char: "🍨", keywords: ["ice cream"] },
      { char: "🍦", keywords: ["soft serve", "ice cream"] },
      { char: "🥐", keywords: ["croissant"] },
      { char: "🥖", keywords: ["baguette", "bread"] },
      { char: "🧀", keywords: ["cheese"] },
      { char: "🥓", keywords: ["bacon"] },
      { char: "🍗", keywords: ["chicken", "drumstick"] },
      { char: "🍖", keywords: ["meat", "bone"] },
      { char: "🌮", keywords: ["taco"] },
      { char: "🌯", keywords: ["burrito", "wrap"] },
      { char: "🥙", keywords: ["sandwich", "pita"] },
      { char: "🍜", keywords: ["noodles", "ramen"] },
      { char: "🍣", keywords: ["sushi"] },
      { char: "🥗", keywords: ["salad"] },
      { char: "🍲", keywords: ["stew", "pot"] },
      { char: "🥟", keywords: ["dumpling"] },
      { char: "🍤", keywords: ["shrimp", "tempura"] },
      { char: "🥞", keywords: ["pancakes"] },
      { char: "🧇", keywords: ["waffle"] },
      { char: "🍳", keywords: ["egg", "cooking"] },
    ],
  },
  {
    name: "Nature",
    label: "Nature 🌸",
    emojis: [
      { char: "🌸", keywords: ["blossom", "flower", "cherry"] },
      { char: "🌺", keywords: ["hibiscus", "flower"] },
      { char: "🌻", keywords: ["sunflower"] },
      { char: "🌼", keywords: ["daisy", "flower"] },
      { char: "🌷", keywords: ["tulip", "flower"] },
      { char: "🌹", keywords: ["rose", "flower"] },
      { char: "🥀", keywords: ["wilted rose"] },
      { char: "🌱", keywords: ["seedling", "sprout"] },
      { char: "🌿", keywords: ["herb", "leaf"] },
      { char: "☘️", keywords: ["shamrock", "clover"] },
      { char: "🍀", keywords: ["clover", "luck"] },
      { char: "🍃", keywords: ["leaves", "wind"] },
      { char: "🍂", keywords: ["fallen leaf", "autumn"] },
      { char: "🍁", keywords: ["maple leaf", "autumn"] },
      { char: "🌵", keywords: ["cactus"] },
      { char: "🌴", keywords: ["palm tree"] },
      { char: "🌳", keywords: ["tree"] },
      { char: "🌲", keywords: ["evergreen", "tree"] },
      { char: "🍄", keywords: ["mushroom"] },
      { char: "🌊", keywords: ["wave", "ocean"] },
      { char: "🌈", keywords: ["rainbow"] },
      { char: "☀️", keywords: ["sun", "sunny"] },
      { char: "🌙", keywords: ["moon", "crescent"] },
      { char: "⭐", keywords: ["star"] },
      { char: "🌟", keywords: ["star", "glowing"] },
      { char: "✨", keywords: ["sparkle", "magic"] },
      { char: "💫", keywords: ["dizzy", "sparkle"] },
      { char: "☁️", keywords: ["cloud"] },
      { char: "❄️", keywords: ["snowflake", "snow"] },
      { char: "🔥", keywords: ["fire"] },
      { char: "🪴", keywords: ["plant", "potted"] },
      { char: "🌍", keywords: ["earth", "globe"] },
    ],
  },
  {
    name: "Hearts",
    label: "Hearts 💕",
    emojis: [
      { char: "💕", keywords: ["two hearts"] },
      { char: "💖", keywords: ["sparkling heart"] },
      { char: "💗", keywords: ["growing heart"] },
      { char: "💓", keywords: ["beating heart"] },
      { char: "💞", keywords: ["revolving hearts"] },
      { char: "💘", keywords: ["heart arrow", "cupid"] },
      { char: "💝", keywords: ["heart gift"] },
      { char: "❤️", keywords: ["red heart"] },
      { char: "🧡", keywords: ["orange heart"] },
      { char: "💛", keywords: ["yellow heart"] },
      { char: "💚", keywords: ["green heart"] },
      { char: "💙", keywords: ["blue heart"] },
      { char: "💜", keywords: ["purple heart"] },
      { char: "🖤", keywords: ["black heart"] },
      { char: "🤍", keywords: ["white heart"] },
      { char: "🤎", keywords: ["brown heart"] },
      { char: "💔", keywords: ["broken heart"] },
      { char: "💌", keywords: ["love letter"] },
      { char: "💋", keywords: ["kiss", "lips"] },
      { char: "😍", keywords: ["heart eyes"] },
      { char: "🥰", keywords: ["loving face"] },
      { char: "😘", keywords: ["kiss face"] },
      { char: "💐", keywords: ["bouquet", "flowers"] },
      { char: "💍", keywords: ["ring", "engagement"] },
      { char: "💎", keywords: ["gem", "diamond"] },
      { char: "🎀", keywords: ["bow", "ribbon"] },
      { char: "🩷", keywords: ["pink heart"] },
      { char: "🩵", keywords: ["light blue heart"] },
      { char: "🩶", keywords: ["gray heart"] },
      { char: "💒", keywords: ["wedding", "chapel"] },
      { char: "👩‍❤️‍👨", keywords: ["couple", "love"] },
      { char: "💑", keywords: ["couple", "love"] },
    ],
  },
  {
    name: "Activities",
    label: "Activities 🏃",
    emojis: [
      { char: "🏃", keywords: ["running", "run"] },
      { char: "🚴", keywords: ["cycling", "bike"] },
      { char: "🏊", keywords: ["swimming", "swim"] },
      { char: "🧘", keywords: ["yoga", "meditate"] },
      { char: "🏋️", keywords: ["weightlifting", "gym"] },
      { char: "⚽", keywords: ["soccer", "football"] },
      { char: "🏀", keywords: ["basketball"] },
      { char: "🏈", keywords: ["american football"] },
      { char: "⚾", keywords: ["baseball"] },
      { char: "🎾", keywords: ["tennis"] },
      { char: "🏐", keywords: ["volleyball"] },
      { char: "🎱", keywords: ["pool", "billiards"] },
      { char: "🏓", keywords: ["ping pong", "table tennis"] },
      { char: "🏸", keywords: ["badminton"] },
      { char: "🥊", keywords: ["boxing"] },
      { char: "🥋", keywords: ["martial arts"] },
      { char: "🎯", keywords: ["dart", "target"] },
      { char: "🎮", keywords: ["video game", "controller"] },
      { char: "🎲", keywords: ["dice", "game"] },
      { char: "🎳", keywords: ["bowling"] },
      { char: "🎨", keywords: ["art", "painting"] },
      { char: "🎭", keywords: ["theater", "drama"] },
      { char: "🎬", keywords: ["movie", "film"] },
      { char: "🎤", keywords: ["microphone", "sing"] },
      { char: "🎧", keywords: ["headphones", "music"] },
      { char: "🎸", keywords: ["guitar", "music"] },
      { char: "🥁", keywords: ["drum", "music"] },
      { char: "🎹", keywords: ["piano", "keyboard"] },
      { char: "🎺", keywords: ["trumpet", "music"] },
      { char: "🎷", keywords: ["saxophone", "music"] },
      { char: "🏹", keywords: ["archery", "bow"] },
      { char: "🎣", keywords: ["fishing"] },
    ],
  },
  {
    name: "Faces",
    label: "Faces 😍",
    emojis: [
      { char: "😀", keywords: ["grinning", "happy"] },
      { char: "😃", keywords: ["smile", "happy"] },
      { char: "😄", keywords: ["laugh", "happy"] },
      { char: "😁", keywords: ["grin", "happy"] },
      { char: "😆", keywords: ["laughing", "happy"] },
      { char: "😅", keywords: ["sweat smile"] },
      { char: "😂", keywords: ["tears of joy", "laugh"] },
      { char: "🤣", keywords: ["rofl", "laugh"] },
      { char: "😊", keywords: ["blush", "smile"] },
      { char: "😇", keywords: ["halo", "angel"] },
      { char: "🙂", keywords: ["slight smile"] },
      { char: "🙃", keywords: ["upside down"] },
      { char: "😉", keywords: ["wink"] },
      { char: "😌", keywords: ["relieved"] },
      { char: "😍", keywords: ["heart eyes", "love"] },
      { char: "🥰", keywords: ["loving face"] },
      { char: "😘", keywords: ["kiss"] },
      { char: "😗", keywords: ["kissing"] },
      { char: "😋", keywords: ["yum", "tasty"] },
      { char: "😜", keywords: ["winky tongue"] },
      { char: "🤪", keywords: ["zany", "crazy"] },
      { char: "🤑", keywords: ["money face"] },
      { char: "🤗", keywords: ["hug"] },
      { char: "🤭", keywords: ["giggle", "oops"] },
      { char: "🤔", keywords: ["thinking"] },
      { char: "🥳", keywords: ["party", "celebrate"] },
      { char: "🤩", keywords: ["star struck", "excited"] },
      { char: "😎", keywords: ["cool", "sunglasses"] },
      { char: "🥺", keywords: ["pleading", "puppy eyes"] },
      { char: "😴", keywords: ["sleepy", "tired"] },
      { char: "🤤", keywords: ["drooling"] },
      { char: "🥹", keywords: ["holding back tears"] },
    ],
  },
  {
    name: "Objects",
    label: "Objects ✨",
    emojis: [
      { char: "✨", keywords: ["sparkle", "magic"] },
      { char: "💡", keywords: ["idea", "lightbulb"] },
      { char: "🔮", keywords: ["crystal ball", "magic"] },
      { char: "🎀", keywords: ["bow", "ribbon"] },
      { char: "🎁", keywords: ["gift", "present"] },
      { char: "🎉", keywords: ["party", "celebrate"] },
      { char: "🎊", keywords: ["confetti", "party"] },
      { char: "💎", keywords: ["gem", "diamond"] },
      { char: "📿", keywords: ["beads", "prayer"] },
      { char: "👑", keywords: ["crown"] },
      { char: "💄", keywords: ["lipstick", "makeup"] },
      { char: "💅", keywords: ["nails", "manicure"] },
      { char: "👗", keywords: ["dress"] },
      { char: "👠", keywords: ["heels", "shoes"] },
      { char: "🕯️", keywords: ["candle"] },
      { char: "📷", keywords: ["camera", "photo"] },
      { char: "📸", keywords: ["camera flash", "photo"] },
      { char: "🎵", keywords: ["music note"] },
      { char: "🎶", keywords: ["music notes"] },
      { char: "💌", keywords: ["love letter"] },
      { char: "📌", keywords: ["pin"] },
      { char: "✂️", keywords: ["scissors"] },
      { char: "🔑", keywords: ["key"] },
      { char: "🔒", keywords: ["lock"] },
      { char: "💰", keywords: ["money bag"] },
      { char: "💵", keywords: ["cash", "money"] },
      { char: "🛍️", keywords: ["shopping bag"] },
      { char: "🧸", keywords: ["teddy bear"] },
      { char: "🪩", keywords: ["disco ball"] },
      { char: "🗝️", keywords: ["key", "old key"] },
      { char: "📦", keywords: ["box", "package"] },
      { char: "🎈", keywords: ["balloon"] },
    ],
  },
];
