// Shared "copy my list to the clipboard" formatter for every shop-ingredients flow
// (grocery list banner, Shop This Recipe) — same category grouping and copy so the
// pasted list always looks the same no matter where it came from.
import { cleanIngredient } from "./delivery";
import { categorizeIngredient, GROCERY_CATEGORY_META, type GroceryCategory } from "./groceryCategories";

const CLIPBOARD_CATEGORY_ORDER: GroceryCategory[] = ["protein", "produce", "dairy", "pantry"];

export function buildShopClipboardText(
  items: { item: string; quantity: string | null }[],
  heading = "My Cutesy Eats Grocery List 🌸",
): string {
  const byCategory = new Map<GroceryCategory, { item: string; quantity: string | null }[]>();
  for (const item of items) {
    const category = categorizeIngredient(item.item);
    const list = byCategory.get(category) ?? [];
    list.push(item);
    byCategory.set(category, list);
  }

  const lines = [
    heading,
    new Date().toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" }),
    "",
  ];
  for (const category of CLIPBOARD_CATEGORY_ORDER) {
    const categoryItems = byCategory.get(category);
    if (!categoryItems || categoryItems.length === 0) continue;
    lines.push(`${GROCERY_CATEGORY_META[category].emoji} ${GROCERY_CATEGORY_META[category].label}:`);
    for (const item of categoryItems) {
      lines.push(`• ${item.quantity ? `${item.quantity} ` : ""}${cleanIngredient(item.item)}`);
    }
    lines.push("");
  }
  lines.push("Generated by Cutesy Eats 🌸");
  return lines.join("\n").trim();
}
